import { cookies } from "next/headers";
import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { verifyToken } from "@/lib/auth";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

function randomPassword() {
  const chars =
    "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789!@#$%^&*()-_=+";
  let pwd = "";
  for (let i = 0; i < 16; i++) {
    pwd += chars[Math.floor(Math.random() * chars.length)];
  }
  return pwd;
}

export async function POST(req: NextRequest) {
  try {
    const sessionCookie = cookies().get("session")?.value;
    const session = verifyToken(sessionCookie);
    if (!session || session.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json().catch(() => ({}));
    const hints = body?.hints || "";

    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json({
        password: randomPassword(),
        rationale: "Generated locally because OpenAI API key is missing.",
      });
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            "Generate a strong password (16-24 chars) mixing upper/lowercase, numbers, and symbols. Return valid JSON {\"password\": string, \"rationale\": string}. Do not include dangerous content. Avoid easily guessable words.",
        },
        {
          role: "user",
          content: `Create a strong password. ${hints ? `Notes: ${hints}` : ""}`,
        },
      ],
      response_format: { type: "json_object" },
      temperature: 0.5,
    });

    const raw = completion.choices[0].message.content;
    let result;
    try {
      result = raw ? JSON.parse(raw) : null;
    } catch {
      result = null;
    }

    if (!result?.password) {
      return NextResponse.json({
        password: randomPassword(),
        rationale: "Fallback password generated locally.",
      });
    }

    return NextResponse.json({
      password: result.password,
      rationale: result.rationale || "Generated by AI for strength and randomness.",
    });
  } catch (error: any) {
    console.error("Password generation error:", error);
    return NextResponse.json(
      {
        password: randomPassword(),
        rationale: "Fallback password generated locally due to an error.",
        error: error.message || "Failed to generate password",
      },
      { status: 200 }
    );
  }
}
